"use client";

import React, { useEffect } from "react";
import { useAuthStore } from "@multica/core/auth";
import { useWorkspaceStore } from "@multica/core/workspace";
import { WorkspaceIdProvider } from "@multica/core/hooks";
import { api } from "@multica/core/api";
import { useAppStore } from "@/stores/app-store";

// PAT is dynamically generated by the embedded multica-server on each startup
// and saved to userData/multica-pat.json. Preload exposes it via CabinetDesktop.
function getOwnerPAT(): string {
  if (typeof window !== "undefined") {
    const desktop = (window as any).CabinetDesktop;
    if (desktop?.multicaPAT) {
      return desktop.multicaPAT;
    }
  }
  // Dev mode fallback — used when running via `npm run dev` without Electron
  return "mul_8ffe8a61758687cd5bbcfe18d9d30ed9f9a59bbf";
}
const OWNER_PAT = getOwnerPAT();
const AUTO_LOGIN_MAX_RETRIES = 8;
const AUTO_LOGIN_BASE_DELAY_MS = 600;

function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function MulticaUnavailable({
  onRetry,
  onBackHome,
}: {
  onRetry: () => void;
  onBackHome: () => void;
}) {
  return (
    <div className="flex h-full items-center justify-center p-6">
      <div className="max-w-md rounded-lg border bg-card p-6 text-center">
        <div className="text-base font-semibold">Multica 服务不可用</div>
        <p className="mt-2 text-sm text-muted-foreground">
          已切换为离线模式。你可以继续使用 Cabinet 知识库、编辑器和 AI 面板。
        </p>
        <div className="mt-4 flex items-center justify-center gap-2">
          <button
            type="button"
            className="rounded-md bg-primary px-3 py-2 text-sm text-primary-foreground"
            onClick={onBackHome}
          >
            返回知识库
          </button>
          <button
            type="button"
            className="rounded-md border px-3 py-2 text-sm"
            onClick={onRetry}
          >
            重试连接
          </button>
        </div>
      </div>
    </div>
  );
}

class MulticaRenderErrorBoundary extends React.Component<
  { children: React.ReactNode; fallback: React.ReactNode; resetKey: string },
  { hasError: boolean }
> {
  constructor(props: { children: React.ReactNode; fallback: React.ReactNode; resetKey: string }) {
    super(props);
    this.state = { hasError: false };
  }

  static getDerivedStateFromError(error: Error) {
    console.error("[MulticaRenderErrorBoundary]", error);
    return { hasError: true };
  }

  componentDidUpdate(prevProps: { resetKey: string }) {
    if (prevProps.resetKey !== this.props.resetKey && this.state.hasError) {
      this.setState({ hasError: false });
    }
  }

  render() {
    if (this.state.hasError) {
      return this.props.fallback;
    }
    return this.props.children;
  }
}

export function MulticaAuthGuard({ children }: { children: React.ReactNode }) {
  const user = useAuthStore((s) => s.user);
  const isLoading = useAuthStore((s) => s.isLoading);
  const workspace = useWorkspaceStore((s) => s.workspace);
  const section = useAppStore((s) => s.section);
  const setSection = useAppStore((s) => s.setSection);

  // 个人模式：自动用 PAT 登录，无需手动操作
  useEffect(() => {
    if (isLoading || user) return;

    let disposed = false;

    async function autoLogin() {
      localStorage.setItem("multica_token", OWNER_PAT);
      api.setToken(OWNER_PAT);

      for (let attempt = 1; attempt <= AUTO_LOGIN_MAX_RETRIES; attempt += 1) {
        try {
          const me = await api.getMe();
          const wsList = await api.listWorkspaces();
          if (disposed) return;
          const wsId = localStorage.getItem("multica_workspace_id");
          useWorkspaceStore.getState().hydrateWorkspace(wsList, wsId);
          useAuthStore.getState().setUser(me);
          return;
        } catch (error) {
          const err = error instanceof Error ? error.message : String(error);
          console.error("[multica] PAT auto-login failed", {
            attempt,
            maxAttempts: AUTO_LOGIN_MAX_RETRIES,
            error: err,
          });

          if (attempt < AUTO_LOGIN_MAX_RETRIES) {
            const delay = AUTO_LOGIN_BASE_DELAY_MS * attempt;
            await sleep(delay);
          }
        }
      }

      if (disposed) return;
      // 后端暂不可用：进入离线兜底，避免白屏/崩溃
      const now = new Date().toISOString();
      useWorkspaceStore.getState().hydrateWorkspace([
        {
          id: "local-workspace",
          name: "Owner (Offline)",
          slug: "local-offline",
          description: "Local fallback workspace when Multica backend is unavailable.",
          context: null,
          settings: {},
          repos: [],
          issue_prefix: "LOCAL",
          created_at: now,
          updated_at: now,
        },
      ], "local-workspace");
      useAuthStore.getState().setUser({
        id: "local-owner",
        email: "owner@local",
        name: "Owner",
      } as any);
    }

    void autoLogin();
    return () => {
      disposed = true;
    };
  }, [isLoading, user]);

  if (isLoading || !user || !workspace) {
    return (
      <div className="flex items-center justify-center h-full">
        <div className="animate-pulse text-sm text-muted-foreground">加载中...</div>
      </div>
    );
  }

  const unavailableFallback = (
    <MulticaUnavailable
      onRetry={() => window.location.reload()}
      onBackHome={() => setSection({ type: "home" })}
    />
  );

  return (
    <MulticaRenderErrorBoundary
      resetKey={`${section.type}:${(section as any).id || (section as any).slug || ""}`}
      fallback={unavailableFallback}
    >
      <WorkspaceIdProvider wsId={workspace.id}>
        {children}
      </WorkspaceIdProvider>
    </MulticaRenderErrorBoundary>
  );
}
